name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # Linting
      - name: ESLint
        run: npm run lint

      - name: StyleLint
        run: npm run stylelint

      # Testing
      - name: Unit tests
        run: npm run test:unit

      - name: UI build storybook
        run: npm run storybook:build

      - name: UI tests
        run: npm run test:ui:ci

      # Build
      - name: Build production
        run: npm run build:prod
